//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Shared.Error
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Shared.Error.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome não pode ser vazio.
        /// </summary>
        public static string NAME_EMPTY
        {
            get
            {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome muito curto.
        /// </summary>
        public static string NAME_TOOSHORT
        {
            get
            {
                return ResourceManager.GetString("NAME_TOOSHORT", resourceCulture);
            }
        }

        public static string PRICE_NEGATIVE
        {
            get
            {
                return ResourceManager.GetString("PRICE_NEGATIVE", resourceCulture);
            }
        }

        public static string STOCK_NEGATIVE
        {
            get
            {
                return ResourceManager.GetString("STOCK_NEGATIVE", resourceCulture);
            }
        }

        public static string STOCK_INSUFFICIENT
        {
            get
            {
                return ResourceManager.GetString("STOCK_INSUFFICIENT", resourceCulture);
            }
        }

        public static string DISCOUNT_INVALID
        {
            get
            {
                return ResourceManager.GetString("DISCOUNT_INVALID", resourceCulture);
            }
        }

        public static string CATEGORY_ALREADY_EXISTS
        {
            get
            {
                return ResourceManager.GetString("CATEGORY_ALREADY_EXISTS", resourceCulture);
            }
        }

        public static string CATEGORY_NOT_FOUND
        {
            get
            {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }

        public static string PRODUCT_NOT_FOUND
        {
            get
            {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }

        public static string SERVER_ERROR
        {
            get
            {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
    }
}
